from django.urls import path

from orders.views import (
    CartView,
    CartItemDeleteView,
    ContactListCreateView,
    ContactDetailView,
    OrderCreateView,
    OrderListView,
    OrderDetailView,
    SupplierOrderListView,
    SupplierOrderStatusView,
)

urlpatterns = [
    path(
        "cart/",
        CartView.as_view(),
        name="cart",
    ),
    path(
        "cart/items/<int:pk>/",
        CartItemDeleteView.as_view(),
        name="cart-item-delete",
    ),
    path(
        "contacts/",
        ContactListCreateView.as_view(),
        name="contact-list-create",
    ),
    path(
        "contacts/<int:pk>/",
        ContactDetailView.as_view(),
        name="contact-detail",
    ),
    path(
        "orders/",
        OrderCreateView.as_view(),
        name="order-create",
    ),
    path(
        "orders/history/",
        OrderListView.as_view(),
        name="order-list",
    ),
    path(
        "orders/<int:pk>/",
        OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "shop/orders/",
        SupplierOrderListView.as_view(),
        name="supplier-order-list",
    ),
    path(
        "shop/orders/<int:pk>/status/",
        SupplierOrderStatusView.as_view(),
        name="supplier-order-status",
    ),
]
