# Generated by Django 6.0.7 on 2026-09-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Отчество"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=150, verbose_name="Улица")),
                ("house", models.CharField(max_length=20, verbose_name="Дом")),
                (
                    "building",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Корпус"
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Строение"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Квартира"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ("-created_at",),
            },
        ),
    ]
