# Generated by Django 6.0.7 on 2026-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
    ]
